package com.herokuapp.ddspace.model;

public class LikesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.PARENT_ID
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.TYPE
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.USER_ID
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.PARENT_ID
     *
     * @return the value of LIKES.PARENT_ID
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.PARENT_ID
     *
     * @param parentId the value for LIKES.PARENT_ID
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.TYPE
     *
     * @return the value of LIKES.TYPE
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.TYPE
     *
     * @param type the value for LIKES.TYPE
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.USER_ID
     *
     * @return the value of LIKES.USER_ID
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.USER_ID
     *
     * @param userId the value for LIKES.USER_ID
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}