package com.herokuapp.ddspace.model;

public class Likes extends LikesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKES.GMT_CREATE
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKES.GMT_CREATE
     *
     * @return the value of LIKES.GMT_CREATE
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKES.GMT_CREATE
     *
     * @param gmtCreate the value for LIKES.GMT_CREATE
     *
     * @mbg.generated Wed Feb 19 19:03:29 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}